### ISSUE TITLE
Bulk create customer

### ISSUE THREAD

**Issue by Pauloparakleto** [Purple-Stock/open-erp#135]
User should create many customers at once using a CSV file.

**Comment by Pauloparakleto** [comment]
@puppe1990 👏🏻 👏🏻 👏🏻

**Comment by puppe1990** [comment]
@jhonnatas 👏🏻 👏🏻 👏🏻 <---- @Pauloparakleto

**Comment by Pauloparakleto** [comment]
@jhonnatas 👏🏻 👏🏻 👏🏻 👏🏻 Great rspecs scenarios providing not only success scenarios but also the failing ones.

**Comment by jhonnatas** [comment]
@Pauloparakleto Thank you for the feedback!
