### ISSUE TITLE
Potential mismatch between ran migrations and schema

### ISSUE THREAD

**Issue by PavarinE** [Purple-Stock/open-erp#23]
Hey guys, 

I was working on fixing and enhancing the Docker approach to run the project and I noticed something that is, at least, curious. 
After setting up the database with `rails db:create` and loading the initial schema with `rails db:schema:load` there are still migrations pending to be applied as you can see if you ran `db:migrate:status`: 

![image](https://github.com/Purple-Stock/open-erp/assets/7964698/07bbc284-5cef-47a7-b135-ab8bdd65d12b)

Ideally, this should not be happening. My guess is that whomever commited the last migrations, forgot to also commit the changes to the **schema.rb**, including the timestamps of the last applied migrations. 

Note that running `rails db:migrate` **is not** the correct approach to set up new environments, [according to Rails official documentation](https://edgeguides.rubyonrails.org/active_record_migrations.html#what-are-schema-files-for-questionmark).

**Comment by Pauloparakleto** [comment]
@PavarinE thanks to examining this issue, I think this is the newest schema migration I have worked with.
