### ISSUE TITLE
Permitir definir metas de vendas mensais

### ISSUE THREAD

**Issue by puppe1990** [Purple-Stock/open-erp#259]
Cadastro de metas de vendas:
- Mês/ano
- Meta faturamento Mensal
- Ticket Médio(faturamento mensal/ quantidade de pedidos mensal)
Tela pŕopria para editar as metas.
Mostrar a informação da meta de vendas no dashboard.

**Comment by puppe1990** [comment]
Tela própria.

**Comment by Pauloparakleto** [comment]
Qual a quantidade deve ser vendida no mês dado o Faturamento esperado e o Ticket Médio.
Cada mês possui sua própria meta de vendas.
CRUD meta de vendas.
"A meta de vendas desse mês a definir".
Exemplo: Outubro de 2023 tem meta e venda diferente de Outuro de 2024.
