### ISSUE TITLE
Caixa com a contagem total

### ISSUE THREAD

**Issue by puppe1990** [Purple-Stock/open-erp#413]
Colocar uma caixa com a contagem total nos "Pedidos Concluidos(Pagos)", "Pedidos Feitos(checados e verificados)", "Pedidos Impressos (zerar ao final do dia)", "Pedidos Pendentes" e "Pedidos Em andamento(Pagos)"

**Comment by Pauloparakleto** [comment]
O que tem filtro soma pelo filtro, os que não tem soma o total disponivel.
