### ISSUE TITLE
integrar meio de pagamento 

### ISSUE THREAD

**Issue by puppe1990** [Purple-Stock/open-erp#62]
Integrar meios de pagamentos para recorrência da iugu.

Referência:
https://dev.iugu.com/reference/metadados

**Comment by JonatascNascimento** [comment]
@puppe1990 vai usar a API da iugu pra fazer cobranças avulsas e o cadastro do cliente fica só aqui dentro, ou vai gerar algum tipo de cadastro e/ou recorrência por eles mesmos?

**Comment by puppe1990** [comment]
A ideia que seja por assinatura pagamento mensal. Daí não tenho tanto conhecimento da API da iugu para configurar essa parte.

**Comment by puppe1990** [comment]
Estudar meio de pagamento com melhores taxas.
