### ISSUE TITLE
Como rodar o app?

### ISSUE THREAD

**Issue by osmaircoelho** [Purple-Stock/open-erp#81]
Olá primeiramente parabéns pelo projeto?

Gostaria de rodar esse projeto, procurei na internet mas não encontrei, perguntei nos grupos e fóruns porem ninguém responde, alguém ai poderia me ajudar?

**Comment by osmaircoelho** [comment]
Ola segui sim, porem para voce entender, eu tenho o windwos 10, e estava tentando rodar no win, porem eu vi que estava dando muito erro, mesmo assim eu nao rodei, vou tentar rodar com o docker, parece que eh isso que tem la na raiz do projeto, obrigado pela ajuda logo menos posto no novidades aqui.

**Comment by osmaircoelho** [comment]
Tem o passo a passo como rodar utilizando o Docker? eu Instalei o Docker e esta rodando o container porem o banco de dados não sei configurar.

desculpe as duvidas mas não tenho conhecimento e já busquei na internet sem sucesso.

![image](https://user-images.githubusercontent.com/2856340/174412326-29845d03-1947-4e46-b3b0-a2905ac893c6.png)

![image](https://user-images.githubusercontent.com/2856340/174412357-801f6f25-d515-4409-884a-61c4c77705b1.png)

**Comment by JonatascNascimento** [comment]
Eae @osmaircoelho, tudo bem?
Primeiramente, desculpa a demora pra responder aqui.

Nós acabamos de subir uma configuração do docker pra main, agora usando o compose vc deve conseguir se conectar.

Depois de atualizar a sua branch local, rode um `docker-compose build` pra buildar a imagem do docker pra vc.

Terminando o processo, só executar um `docker-compose up` e ele vai subir o postgres e o redis.

Depois que os containers subirem, vc pode abrir mais uma aba do seu terminal pra subir o rails server e já consegue conectar no localhost.

Caso vc tente se conectar no localhost e tenha um retorno de erro de conexão com o postgre, pela porta 5432, execute o comando de parar a execução do postgres local, pois como ele usa a porta padrão, pode conflitar com o que o docker subiu.

Qualquer coisa, pode me responder por aqui.

Abraços.

**Comment by osmaircoelho** [comment]
Até parece que tu estava lendo minha mente, daqui a pouco vou testar então, muito obrigado pela resposta.

**Comment by osmaircoelho** [comment]
![image](https://user-images.githubusercontent.com/2856340/177228470-db1f67c0-4a98-43c3-97e2-6c81215bab3c.png)
o que eu fiz? baixei em uma nova pasta o projeto e quando eu rodo `docker-compose build`  isso acontece isso.

bora pesquisar e ver o que esta acontecendo!!!

**Comment by JonatascNascimento** [comment]
Eae @osmaircoelho, descobri aqui o que aconteceu.

Eu clonei o repositório em uma outra máquina e tive esse mesmo problema.
O lance é que, na minha ultima resposta, eu acabei pulando um passo do docker ... =/

Antes de executar `compose` vc precisa buildar as imagens que estão configuradas no dockerfile.
Para isso, vc precisa executar `docker image build -t open_erp .` e por fim `docker-compose up`.

Como as imagens já estão sendo construidas no primeiro comando, não há a necessidade de rodar o `docker-compose build'

**Comment by osmaircoelho** [comment]
Qual diretório tenho que executar? pois esse comando não seu certo 
estou dentro da pasta open_erp

![image](https://user-images.githubusercontent.com/2856340/177454082-7ef0c141-0581-4009-89c8-864705a262ca.png)

**Comment by JonatascNascimento** [comment]
@osmaircoelho É nesse repositório mesmo.
É que faltou um ponto (.) no final do comando.

docker image build -t open_erp .

**Comment by osmaircoelho** [comment]
Maneiro agora deu certo, amanho continuo, obrigado pela resposta
![image](https://user-images.githubusercontent.com/2856340/177455674-b4ebe18a-857d-483a-8d2f-50621c053d0a.png)

**Comment by JonatascNascimento** [comment]
Booa.

Qualquer coisa, só chamar aqui.

**Comment by osmaircoelho** [comment]
Deu tudo certo e agora qual a proxima etapa, para rodar o app no navegador
desculpe nao conheco muito bem o docker

![image](https://user-images.githubusercontent.com/2856340/177456469-cd4dcc82-188e-4fc0-8ffc-90bd41a7ed09.png)

**Comment by JonatascNascimento** [comment]
Certo, agora que os containers estão de pé, vc precisa abrir uma nova aba do terminal e subir o rails server, com o comando `rails s`.
Assim que o server subir, vc consegue acessar a página pelo `localhost:3000`.

**Comment by osmaircoelho** [comment]
Eu preciso rodar esse comando `bin/rails s` dentro do servidor
`docker run -it open_erp bash`

![image](https://user-images.githubusercontent.com/2856340/177458730-d0dce25d-1ca2-4abe-82c9-715a987c23d4.png)


eu rodei dentro do win e olha o que houve
![image](https://user-images.githubusercontent.com/2856340/177458810-30802802-512c-4db5-a4e2-9337371f3bc7.png)

**Comment by JonatascNascimento** [comment]
Você precisa rodar ele fora do server, da forma que fez mesmo.

Em alguns casos, quando as `gems` não estão instaladas ele vai te pedir pra instalar elas por meio do `bundle install`.
Mas depois de executar a instalação das `gems`, vc pode executar o comando de subir o server de novo que vai funcionar.

**Comment by osmaircoelho** [comment]
Aos trancos e barrancos 

![image](https://user-images.githubusercontent.com/2856340/177459272-ce81f767-a59e-4635-9a12-096db45290b4.png)

**Comment by osmaircoelho** [comment]
Era isso que tinha que rodar? problema que o localhost:3000 nao esta abrindo
![image](https://user-images.githubusercontent.com/2856340/177459488-0f916a45-20db-4720-9915-9368798ed803.png)

**Comment by JonatascNascimento** [comment]
Era isso mesmo.

O que retorna pra vc quando acessa o localhost?

**Comment by JonatascNascimento** [comment]
Aah, já sei o que é...

Abre uma outra guia do terminal e executa esse comando aqui:

`RAILS_ENV=development rake db:create db:migrate`

Isso vai criar e migrar a base local.

Ai sim vc vai conseguir acessar o localhost.

**Comment by osmaircoelho** [comment]
esta dando esse erro, estou rodando tudo no servidor pois no win esta dando erro ao rodar o bin/rails s

![image](https://user-images.githubusercontent.com/2856340/177460264-274f8b03-b616-4349-a889-95e69e94da4d.png)

**Comment by osmaircoelho** [comment]
Amanha nos continuamos, obrigado pela interação.

**Comment by JonatascNascimento** [comment]
Eu preciso ver melhor isso aqui, mas podem ser algumas coisas.

1 - Caso o comando `bin/rails s` esteja dando erro no win, tenta executar só `rails s`.
2 - Você precisa ver se o seu postgres local está de pé e, se estiver, da um `stop` nele, porque a porta 5432 é a padão dele e pode estar conflitando.

**Comment by JonatascNascimento** [comment]
> Amanha nos continuamos, obrigado pela interação.

Fechou.

**Comment by OsmairDev** [comment]
Olá bom dia, será que tem tempo para dar uma ajuda hoje depois das 7pm?

**Comment by osmaircoelho** [comment]
De acordo com as pesquisas tenho que liberar algo no postgres para conexão externa.

pior que nem localhost esta carregando

https://www.linuxfixes.com/2021/12/solved-docker-is-server-running-on-host.html
https://unix.stackexchange.com/questions/589474/is-the-server-running-on-host-localhost-1-and-accepting-tcp-ip-connections

**Comment by JonatascNascimento** [comment]
Olá, @osmaircoelho, tudo bem?

Lembro que quando tive esse erro na hora de acessar o localhost ou fazer alguma ação no banco, eu fiz o `stop` do Postegres local, para não ter o conflito de porta com o Postgres que está no docker.

Segundo o link abaixo, para descer o Postgres no windows, vc precisa acessar o diretório dele e dar o comando `stop` no final.

`pg_ctl -D "C:\Program Files (x86)\PostgreSQL\9.6\data" stop`

https://atendimento.tecnospeed.com.br/hc/pt-br/articles/360012608093-PostgreSQL-Comandos-para-START-STOP-e-RESTART-do-servidor-de-banco-de-dados-Postgres

**Comment by osmaircoelho** [comment]
Ola @JonatascNascimento tudo bem?

entao eu nao estou rodando o postgres no win 10 local, sim o postgre esta instalado, porem os servicos do postgre estao parados, estou utilizando o postgres no docker mesmo.

o que eu percebi, fiz os procedicmento constados ai em cima, porem infelizmente ainda nao funcionou, segui um tutorial na internet com se conectar no postgres via docker.

mas eu percebi que quando subo a aplicacao, nem mesmo no localhost esta carregando a aplicacao, era pelo menos mostrar que carregou entao, vou descarcar a em primeiro momento a conexao com o banco de dados em vou me concentrar em exibir algo na localhost.

se preferir me add no discord `Ozzy#2387 `, vou tentar agora descobrir porque o localhos nao carregar a aplicacao na web.

Obrigado.

**Comment by osmaircoelho** [comment]
Faltou publicar o arquivo .env

**Comment by osmaircoelho** [comment]
finalmente depois de muitos erros consegui fazer ele quase funcionar, infelizmente deixei de lado o Docker pois tentei de diversas formas fazer isso funcionar e nada, ai resolvi instalar no windows 10 mesmo, mas ainda falta bastante.

![image](https://user-images.githubusercontent.com/2856340/186415441-dbd564b5-409c-46de-986f-82ccd6504ca1.png)
